import { createEnv, generateExample, validateEnvFile } from '../src/core'
import { str, num, bool, url, port, email } from '../src/validators'
import { EnvValidationError } from '../src/errors'

// ---------------------------------------------------------------------------
// createEnv — happy paths
// ---------------------------------------------------------------------------
describe('createEnv() — valid input', () => {
  it('returns typed values from process.env substitute', () => {
    const env = createEnv({
      schema: {
        HOST: str(),
        PORT: port(),
        DEBUG: bool(),
      },
      env: { HOST: 'localhost', PORT: '4000', DEBUG: 'true' },
    })
    expect(env.HOST).toBe('localhost')
    expect(env.PORT).toBe(4000)
    expect(env.DEBUG).toBe(true)
  })

  it('uses defaults for missing optional variables', () => {
    const env = createEnv({
      schema: {
        PORT: port({ default: 3000 }),
        DEBUG: bool({ default: false }),
        TAG: str({ default: 'latest' }),
      },
      env: {},
    })
    expect(env.PORT).toBe(3000)
    expect(env.DEBUG).toBe(false)
    expect(env.TAG).toBe('latest')
  })

  it('returns a frozen object', () => {
    const env = createEnv({ schema: { X: str() }, env: { X: 'hello' } })
    expect(Object.isFrozen(env)).toBe(true)
  })

  it('treats empty string same as missing', () => {
    const env = createEnv({
      schema: { PORT: port({ default: 8080 }) },
      env: { PORT: '' },
    })
    expect(env.PORT).toBe(8080)
  })
})

// ---------------------------------------------------------------------------
// createEnv — error paths
// ---------------------------------------------------------------------------
describe('createEnv() — invalid input', () => {
  it('throws EnvValidationError when required variable is missing', () => {
    expect(() =>
      createEnv({ schema: { API_KEY: str() }, env: {} }),
    ).toThrow(EnvValidationError)
  })

  it('collects multiple errors in one throw', () => {
    try {
      createEnv({
        schema: {
          A: str(),
          B: num(),
          C: port(),
        },
        env: { B: 'not-a-number', C: '99999' },
      })
      fail('should have thrown')
    } catch (e) {
      expect(e).toBeInstanceOf(EnvValidationError)
      const err = e as EnvValidationError
      // A is missing, B is invalid, C is out of range
      expect(err.errors.length).toBe(3)
      expect(err.errors.map((x) => x.field)).toEqual(expect.arrayContaining(['A', 'B', 'C']))
    }
  })

  it('masks secret values in error output', () => {
    try {
      createEnv({
        schema: { TOKEN: str({ secret: true, minLength: 20 }) },
        env: { TOKEN: 'short' },
      })
    } catch (e) {
      const err = e as EnvValidationError
      expect(err.errors[0]?.received).toBe('[secret]')
    }
  })

  it('calls onError before throwing', () => {
    const onError = jest.fn()
    expect(() =>
      createEnv({
        schema: { X: str() },
        env: {},
        onError,
      }),
    ).toThrow(EnvValidationError)
    expect(onError).toHaveBeenCalledTimes(1)
    expect(onError.mock.calls[0]?.[0]).toHaveLength(1)
  })

  it('does not throw when skipValidation is true', () => {
    expect(() =>
      createEnv({
        schema: { X: str() },
        env: {},
        skipValidation: true,
      }),
    ).not.toThrow()
  })
})

// ---------------------------------------------------------------------------
// generateExample
// ---------------------------------------------------------------------------
describe('generateExample()', () => {
  it('generates header comment', () => {
    const out = generateExample({})
    expect(out).toContain('# Auto-generated by envx')
  })

  it('shows default values', () => {
    const out = generateExample({ PORT: port({ default: 3000 }) })
    expect(out).toContain('PORT=3000')
  })

  it('masks secrets', () => {
    const out = generateExample({ TOKEN: str({ secret: true }) })
    expect(out).toContain('TOKEN=[secret]')
  })

  it('leaves required fields blank', () => {
    const out = generateExample({ DB_URL: url() })
    expect(out).toMatch(/DB_URL=\s*(\n|$)/)
  })

  it('includes description as a comment', () => {
    const out = generateExample({
      API_KEY: str({ description: 'Your API key', secret: true }),
    })
    expect(out).toContain('# Your API key')
  })
})

// ---------------------------------------------------------------------------
// validateEnvFile
// ---------------------------------------------------------------------------
describe('validateEnvFile()', () => {
  it('returns empty array for valid input', () => {
    const errors = validateEnvFile(
      { HOST: 'localhost', PORT: '3000' },
      { HOST: str(), PORT: port() },
    )
    expect(errors).toHaveLength(0)
  })

  it('returns errors for invalid fields', () => {
    const errors = validateEnvFile(
      { PORT: 'not-a-port' },
      { PORT: port(), HOST: str() },
    )
    // PORT invalid, HOST missing and required
    expect(errors.length).toBe(2)
  })

  it('skips optional fields that are absent', () => {
    const errors = validateEnvFile({}, { PORT: port({ default: 3000 }) })
    expect(errors).toHaveLength(0)
  })
})

// ---------------------------------------------------------------------------
// EnvValidationError
// ---------------------------------------------------------------------------
describe('EnvValidationError', () => {
  it('has correct name', () => {
    const err = new EnvValidationError([{ field: 'X', message: 'oops', received: undefined }])
    expect(err.name).toBe('EnvValidationError')
  })

  it('is instanceof Error', () => {
    const err = new EnvValidationError([])
    expect(err).toBeInstanceOf(Error)
  })

  it('message contains field name', () => {
    const err = new EnvValidationError([
      { field: 'DATABASE_URL', message: 'is required but missing', received: undefined },
    ])
    expect(err.message).toContain('DATABASE_URL')
  })

  it('exposes errors array', () => {
    const fieldErr = { field: 'X', message: 'bad', received: 'val' }
    const err = new EnvValidationError([fieldErr])
    expect(err.errors).toHaveLength(1)
    expect(err.errors[0]).toEqual(fieldErr)
  })
})

// ---------------------------------------------------------------------------
// createEnv — optional spec with no default (defensive branch)
// ---------------------------------------------------------------------------
describe('createEnv() — optional spec with no default', () => {
  it('sets field to undefined when optional and absent', () => {
    // Construct a spec directly that is not required but has no default
    const optionalSpec = {
      _type: undefined as unknown as string,
      _required: false,
      _default: undefined,
      _secret: false,
      _description: undefined,
      _parse: (raw: string) => raw,
      _validate: () => {},
    }
    const env = createEnv({
      schema: { OPTIONAL: optionalSpec },
      env: {},
      skipValidation: true,
    })
    expect((env as Record<string, unknown>)['OPTIONAL']).toBeUndefined()
  })
})

// ---------------------------------------------------------------------------
// Complex integration — real-world-like schema
// ---------------------------------------------------------------------------
describe('integration: full schema', () => {
  const schema = {
    DATABASE_URL: url(),
    PORT: port({ default: 3000 }),
    NODE_ENV: str({ choices: ['development', 'production', 'test'], default: 'development' }),
    DEBUG: bool({ default: false }),
    API_KEY: str({ secret: true }),
    MAX_RETRIES: num({ default: 3, min: 0, max: 10 }),
    ADMIN_EMAIL: email({ default: 'admin@example.com' }),
  }

  it('succeeds with all required vars provided', () => {
    const env = createEnv({
      schema,
      env: {
        DATABASE_URL: 'postgresql://localhost/mydb',
        API_KEY: 'super-secret-key',
      },
    })
    expect(env.DATABASE_URL).toBe('postgresql://localhost/mydb')
    expect(env.PORT).toBe(3000)
    expect(env.NODE_ENV).toBe('development')
    expect(env.DEBUG).toBe(false)
    expect(env.API_KEY).toBe('super-secret-key')
    expect(env.MAX_RETRIES).toBe(3)
    expect(env.ADMIN_EMAIL).toBe('admin@example.com')
  })

  it('fails when required vars are missing', () => {
    expect(() => createEnv({ schema, env: {} })).toThrow(EnvValidationError)
  })

  it('validates NODE_ENV choices', () => {
    expect(() =>
      createEnv({
        schema,
        env: { DATABASE_URL: 'https://db.example.com', API_KEY: 'key', NODE_ENV: 'staging' },
      }),
    ).toThrow(EnvValidationError)
  })
})
