import { EnvValidationError, type FieldError } from './errors.js'
import type { ValidatorSpec } from './validators.js'

// ---------------------------------------------------------------------------
// Schema helpers
// ---------------------------------------------------------------------------

/** A schema maps env var names to their validator specs. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Schema = Record<string, ValidatorSpec<any>>

/**
 * Infer the output type from a schema.
 * Required validators produce `T`, optional ones produce `T` (since the
 * default fills the gap — callers never receive `undefined`).
 */
export type InferEnv<S extends Schema> = {
  readonly [K in keyof S]: S[K] extends ValidatorSpec<infer T> ? T : never
}

// ---------------------------------------------------------------------------
// createEnv options
// ---------------------------------------------------------------------------

/** Options accepted by {@link createEnv}. */
export interface CreateEnvOptions<S extends Schema> {
  /** The schema describing every expected variable and its validator. */
  schema: S
  /**
   * Source of raw string values. Defaults to `process.env`.
   * Override for testing or edge-runtime environments.
   */
  env?: Record<string, string | undefined>
  /**
   * When `true`, `createEnv` returns `null` instead of throwing on failure.
   * Useful for unit tests that want to inspect the error.
   * @default false
   */
  skipValidation?: boolean
  /**
   * Custom reporter called before throwing {@link EnvValidationError}.
   * Receives the structured list of errors so you can log them however you like.
   */
  onError?: (errors: FieldError[]) => void
}

// ---------------------------------------------------------------------------
// createEnv
// ---------------------------------------------------------------------------

/**
 * Validates environment variables against the provided schema and returns a
 * fully-typed, frozen object. Throws {@link EnvValidationError} on failure.
 *
 * @example
 * ```ts
 * export const env = createEnv({
 *   schema: {
 *     DATABASE_URL: url(),
 *     PORT: port({ default: 3000 }),
 *     NODE_ENV: str({ choices: ['development', 'production', 'test'], default: 'development' }),
 *     DEBUG: bool({ default: false }),
 *     API_KEY: str({ secret: true }),
 *   },
 * })
 * ```
 */
export function createEnv<S extends Schema>(options: CreateEnvOptions<S>): InferEnv<S> {
  const { schema, env = process.env, skipValidation = false, onError } = options
  const errors: FieldError[] = []
  const result: Record<string, unknown> = {}

  for (const [field, spec] of Object.entries(schema)) {
    const raw = env[field]

    if (raw === undefined || raw === '') {
      if (spec._default !== undefined) {
        result[field] = spec._default
        continue
      }
      if (!spec._required) {
        // optional with no default → undefined (shouldn't happen given the overloads, but be safe)
        result[field] = undefined
        continue
      }
      errors.push({ field, message: 'is required but missing', received: undefined })
      continue
    }

    try {
      const parsed = spec._parse(raw, field)
      spec._validate(parsed, field)
      result[field] = parsed
    } catch (e) {
      errors.push({
        field,
        message: e instanceof Error ? e.message : String(e),
        received: spec._secret ? '[secret]' : raw,
      })
    }
  }

  if (errors.length > 0 && !skipValidation) {
    onError?.(errors)
    throw new EnvValidationError(errors)
  }

  return Object.freeze(result) as InferEnv<S>
}

// ---------------------------------------------------------------------------
// generateExample
// ---------------------------------------------------------------------------

/**
 * Generates the text content of a `.env.example` file from a schema.
 * Variables without defaults are left blank; those with defaults show the default.
 * Secrets are shown as `[secret]`.
 *
 * @example
 * ```ts
 * import { schema } from './env'
 * import { generateExample } from 'envx'
 * fs.writeFileSync('.env.example', generateExample(schema))
 * ```
 */
export function generateExample(schema: Schema): string {
  const lines: string[] = [
    '# Auto-generated by envx — do not commit real secrets',
    '',
  ]

  for (const [field, spec] of Object.entries(schema)) {
    if (spec._description) {
      lines.push(`# ${spec._description}`)
    }

    let value: string
    if (spec._secret) {
      value = '[secret]'
    } else if (spec._default !== undefined) {
      value = String(spec._default)
    } else {
      value = ''
    }

    lines.push(`${field}=${value}`)
  }

  return lines.join('\n') + '\n'
}

// ---------------------------------------------------------------------------
// validateEnvFile
// ---------------------------------------------------------------------------

/**
 * Given the parsed key=value pairs from a `.env` file and a schema, returns
 * any validation errors without throwing. Useful in CI/pre-deploy checks.
 */
export function validateEnvFile(
  parsed: Record<string, string>,
  schema: Schema,
): FieldError[] {
  const errors: FieldError[] = []

  for (const [field, spec] of Object.entries(schema)) {
    const raw = parsed[field]

    if (raw === undefined || raw === '') {
      if (spec._default !== undefined || !spec._required) continue
      errors.push({ field, message: 'is required but missing', received: undefined })
      continue
    }

    try {
      const parsed2 = spec._parse(raw, field)
      spec._validate(parsed2, field)
    } catch (e) {
      errors.push({
        field,
        message: e instanceof Error ? e.message : String(e),
        received: spec._secret ? '[secret]' : raw,
      })
    }
  }

  return errors
}
